name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: build-${{ github.run_number }}
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/spring-boot-healthcare

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven and run tests
        run: mvn clean package -DskipTests=false

      - name: Upload JAR to GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-healthcare-jar
          path: target/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image with tag
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Show pushed image tag
        run: |
          echo "Docker image pushed: $IMAGE_NAME:$IMAGE_TAG"

      - name: Run Docker container as staging deployment
        run: |
          docker run -d -p 8080:8080 --name healthcare-stage $IMAGE_NAME:$IMAGE_TAG
          sleep 10
          echo "Container logs:"
          docker logs healthcare-stage

      - name: Test health endpoint on staging container
        run: |
          curl --retry 10 --retry-connrefused --retry-delay 3 http://localhost:8080/health

      - name: List running containers
        run: docker ps
