name: CI/CD Pipeline

on:
  push:
    branches: [master] 

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/spring-boot-healthcare

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest

  deploy-to-kind:
    needs: build-test-docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Load Docker image into Kind
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-healthcare:latest
          kind load docker-image ${{ secrets.DOCKER_USERNAME }}/spring-boot-healthcare:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for pod to be ready
        run: |
          kubectl rollout status deployment/healthcare-deployment --timeout=60s
          kubectl get all
